title = "PingalPie's site"
description = "This is website of PingalPie"
default_language = "en"
base_url = "https://pingalpie.vercel.app"
compile_sass = false
build_search_index = false
generate_feed = false
#feed_filename = "atom.xml"

[markdown]	    
highlight_code = true
render_emoji = true

[extra]
